package message

const (
	ErrOpenConn        string = "error when trying to open postgres connection"
	ErrPingConn        string = "error when ping postgres connection"
	ErrQueryGetSpot    string = "error query to get all spots"
	ErrQueryGetSubs    string = "error query to get subs"
	ErrScanSpots       string = "error scan spots"
	ErrScanSubs        string = "error scan subs"
	Russia             string = "\xE2\x98\xAD Russia"
	Worldwide          string = "\xE2\x93\xA6 World"
	Subscribe          string = "\xE2\x88\xBB Subscribe"
	SubList            string = "\xE2\x89\x8B Subscriptions"
	ErrSendInline      string = "error when send inline message"
	Back               string = "Go back"
	ErrUnmarshal       string = "error when marshal db_resource"
	ErrInsertSub       string = "error when insert new sub"
	ErrDeleteSub       string = "error when delete sub"
	ErrSelectWeather   string = "error when select weather by spot"
	ErrZeroRows        string = "error, zero rows found"
	ErrUpdateMess      string = "error when update messages"
	ErrReadAll         string = "error when outill read all"
	ErrHttpGet         string = "error when http get"
	Forecast24         string = "Wind forecast for 24 hours."
	SubMessage         string = "Enter the spot number to subscribe"
	RussiaRegionId     int    = 190
	WorldRegionId      int    = 290
	GetHour            string = "Select time"
	GetSpot            string = "Select spot"
	WrongSpotId        string = "Wrong spot id"
	SubSuccess         string = "You have successfully subscribed!"
	SubDelSuccess      string = "Subscription deleted"
	Delete             string = " \xE2\x98\x92 delete"
	ErrHttpDelRequest  string = "error when send delete request"
	ErrHttpPostRequest string = "error when send post request"
	ErrHttpDelFetch    string = "error when send fetch delete request"
	ImageUrl           string = "/var/www/surfweather.ru/webcams/"
	AviUrl             string = "/var/www/surfweather.ru/webcams/avi/"
)
